name: Mirror S3 to BLOB and R2

on:
  repository_dispatch:
    types: [mztool-updated]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Download mztool.zip from S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp s3://mztool/mztool.zip mztool.zip \
          --region "$AWS_REGION"

    - name: Login no Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Upload do mztool.zip para o Azure Blob
      run: |
        az storage blob upload \
          --account-name mztistorage \
          --container-name mztool \
          --name mztool.zip \
          --file mztool.zip \
          --auth-mode login

    - name: Install Wrangler
      run: |
        npm install -g wrangler

    - name: Upload to Cloudflare R2
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CF_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
      run: |
        wrangler r2 object put "$CF_R2_BUCKET/mztool.zip" \
          --file="./mztool.zip"
